packages:
  - packages/*
  - examples/apps-*
  - benchmarks/dynamic-apps
  - tests/e2e/dynamic-apps

onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - cbor-extract
  - esbuild

overrides:
  '@rivet-dev/agentos-core': 0.0.0-fix-core-spawn-keep-stdin-open.242e11c
  rivetkit: 0.0.0-fix-rivetkit-wasm-serve-config.e2b11f9
  '@rivetkit/rivetkit-wasm': 0.0.0-fix-rivetkit-wasm-serve-config.e2b11f9

catalogs:
  rivetkit:
    rivetkit: 0.0.0-fix-rivetkit-wasm-serve-config.e2b11f9
