packages:
  - packages/*
  - examples/apps-*
  - benchmarks/dynamic-apps
  - tests/e2e/dynamic-apps

onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - cbor-extract
  - esbuild

overrides:
  '@rivet-dev/agentos-core': 0.2.16-rc.3
  '@rivetkit/engine-cli': 2.3.11
  '@rivetkit/react': 2.3.11
  '@rivetkit/rivetkit-wasm': 2.3.11
  rivetkit: 2.3.11

catalogs:
  rivetkit:
    rivetkit: 2.3.11
