import { type ByteCursor } from "../core/byte-cursor.ts";
export declare function readBool(bc: ByteCursor): boolean;
export declare function writeBool(bc: ByteCursor, x: boolean): void;
export declare function readF32(bc: ByteCursor): number;
export declare function writeF32(bc: ByteCursor, x: number): void;
export declare function readF64(bc: ByteCursor): number;
export declare function writeF64(bc: ByteCursor, x: number): void;
export declare function readI8(bc: ByteCursor): number;
export declare function writeI8(bc: ByteCursor, x: number): void;
export declare function readI16(bc: ByteCursor): number;
export declare function writeI16(bc: ByteCursor, x: number): void;
export declare function readI32(bc: ByteCursor): number;
export declare function writeI32(bc: ByteCursor, x: number): void;
export declare function readI64(bc: ByteCursor): bigint;
export declare function writeI64(bc: ByteCursor, x: bigint): void;
export declare function readI64Safe(bc: ByteCursor): number;
export declare function writeI64Safe(bc: ByteCursor, x: number): void;
export declare function readU8(bc: ByteCursor): number;
export declare function writeU8(bc: ByteCursor, x: number): void;
export declare function readU16(bc: ByteCursor): number;
export declare function writeU16(bc: ByteCursor, x: number): void;
export declare function readU32(bc: ByteCursor): number;
export declare function writeU32(bc: ByteCursor, x: number): void;
export declare function readU64(bc: ByteCursor): bigint;
export declare function writeU64(bc: ByteCursor, x: bigint): void;
export declare function readU64Safe(bc: ByteCursor): number;
export declare function writeU64Safe(bc: ByteCursor, x: number): void;
